### ISSUE TITLE
Tries to install PhantomJS 4 times and then finishes script, without error. But it is not installed.

### ISSUE THREAD

**Issue by t202wes** [jakoch/phantomjs-installer#40] opened 2016-10-18 21:02 UTC
When composer tries to run the installPhantomJS method, it just tries to download phantomjs 4 times unsuccessfully. It does not error. The binary is not installed int he correct location.

I'm guessing that it just can't save the file for some reason and it's trying over and over again?

```
> PhantomInstaller\Installer::installPhantomJS
  - Installing phantomjs (2.1.1)
    Downloading: 100%         
  - Installing phantomjs (2.1.1)
    Downloading: 100%         
  - Installing phantomjs (2.1.1)
    Downloading: 100%         
  - Installing phantomjs (2.1.1)
    Downloading: 100%    
```

**Comment by jakoch** [comment] 2016-10-18 22:27
Hey Wes! 

Thank you for reporting the issue.

Which version of `phantomjs-installer` are you using?

What you are describing is not reproducible for me, but must be close to the main download() function: https://github.com/jakoch/phantomjs-installer/blob/master/src/PhantomInstaller/Installer.php#L191-L203

I wonder why it tries to download over and over gain. I would expect the downloader to retry 3 times, then fail, [see Composer/Downloader/FileDownloader L135](https://github.com/composer/composer/blob/master/src/Composer/Downloader/FileDownloader.php#L135)

If it just can't save the file for some reason, it should throw an `\UnexpectedValueException` ([see Composer/Downloader/FileDownloader L159](https://github.com/composer/composer/blob/master/src/Composer/Downloader/FileDownloader.php#L159)), which then bubbles up to the installer, where the try-catch block should catch it as `Exception`.
You should get an error/exception.

**Comment by amitaymolko** [comment] 2016-10-19 13:47
+1
I get the same problem:

````
> PhantomInstaller\Installer::installPhantomJS
  - Installing phantomjs (2.1.1)
    Downloading: Connecting...    Downloading: 0%               Downloading: 5%    Downloading: 10%    Downloading: 15%    Downloading: 20%    Downloading: 25%    Downloading: 30%    Downloading: 35%    Downloading: 40%    Downloading: 45%    Downloading: 50%    Downloading: 55%    Downloading: 60%    Downloading: 65%    Downloading: 70%    Downloading: 75%    Downloading: 80%    Downloading: 85%    Downloading: 90%    Downloading: 95%    Downloading: 100%
  - Installing phantomjs (2.1.1)
    Downloading: Connecting...    Downloading: 0%               Downloading: 5%    Downloading: 10%    Downloading: 15%    Downloading: 20%    Downloading: 25%    Downloading: 30%    Downloading: 35%    Downloading: 40%    Downloading: 45%    Downloading: 50%    Downloading: 55%    Downloading: 60%    Downloading: 65%    Downloading: 70%    Downloading: 75%    Downloading: 80%    Downloading: 85%    Downloading: 90%    Downloading: 95%    Downloading: 100%
  - Installing phantomjs (2.1.1)
    Downloading: Connecting...    Downloading: 0%               Downloading: 5%    Downloading: 10%    Downloading: 15%    Downloading: 20%    Downloading: 25%    Downloading: 30%    Downloading: 35%    Downloading: 40%    Downloading: 45%    Downloading: 50%    Downloading: 55%    Downloading: 60%    Downloading: 65%    Downloading: 70%    Downloading: 75%    Downloading: 80%    Downloading: 85%    Downloading: 90%    Downloading: 95%    Downloading: 100%
  - Installing phantomjs (2.1.1)
    Downloading: Connecting...    Downloading: 0%               Downloading: 5%    Downloading: 10%    Downloading: 15%    Downloading: 20%    Downloading: 25%    Downloading: 30%    Downloading: 35%    Downloading: 40%    Downloading: 45%    Downloading: 50%    Downloading: 55%    Downloading: 60%    Downloading: 65%    Downloading: 70%    Downloading: 75%    Downloading: 80%    Downloading: 85%    Downloading: 90%    Downloading: 95%    Downloading: 100%
```

Ubuntu 16.04 LTS

**Comment by jakoch** [comment] 2016-10-19 20:13
I couldn't reproduce the issue (using `Composer 1.2.1` + `phantomjs-installer 2.1.1-p07`).

Please add the additional catch block after [Line 193](https://github.com/jakoch/phantomjs-installer/blob/master/src/PhantomInstaller/Installer.php#L193) - to check, if the exception isn't bubbling up.
```
} catch (UnexpectedValueException $e) {
   $io->error($e-getMessage());
}
```

**Comment by amitaymolko** [comment] 2016-10-20 08:00
I am using https://github.com/jonnnnyw/php-phantomjs which depends on phantomjs-installer 2.1.1.
After finding this: https://stefanzweifel.io/posts/laravel-forge-php7-and-bzip2/ and installing bz2.
And requiring phantomjs-installer 2.1.1-p07, it works fine.
Thanks

**Comment by jakoch** [comment] 2016-10-20 11:22
Thanks for the feedback. Glad you got it working.
I forgot about the bz2 issue. The problem was mentioned in https://github.com/jakoch/phantomjs-installer/pull/28#issuecomment-208331812 
I will send a PR to php-phantomjs to raise the version to 2.1.1-p07.

@t202wes Does an update to `2.1.1-p07` solve the issue for you, too?

**Comment by amitaymolko** [comment] 2016-10-20 11:31
I have already sent a PR to php-phantomjs :)

**Comment by jakoch** [comment] 2016-10-20 11:36
"two is better than one" :) Closed mine.

**Comment by jakoch** [comment] 2016-10-26 00:29
Issue seems to be resolved. Closing.

**Closed by jakoch** 2016-10-26 00:29 UTC
Labels: verify bug
