### ISSUE TITLE
0770 chmod status

### ISSUE THREAD

**Issue by Trogie** [jakoch/phantomjs-installer#41] opened 2016-10-27 13:01 UTC
Hello, why are the permissions set to 0770 in the code? We build a package that gets installed on server with root:root. 0776 would be a more logical settings and following the other binaries composer makes.

**Comment by jakoch** [comment] 2016-10-27 16:19
Hello Tom.

Ok, let's discuss this...

> why are the permissions set to 0770 in the code?

The permissions are set to 0770 to allow read+write+exec for user and group, but not for others.
0776 means that others get read+write, but not exec permissions.
My 0770 is more secure, than having an others-readable, others-writable binary file.
770 should cover the use-case that users install the Phantom binary as normal user on a production box. This is already a worst case, because Composer is a develop tool, which isn't supposed to run on a production box. It's also a reminder, that users needing to exec the file should be members of a group having access to it. 

When your other binaries have 0776, then the current umask must be 0001,
because Composer subtracts permissions using `0777 & ~umask()`.
776 is not a good setting for binaries on a production box.

It's not clear to me why 0776 would be a more logical setting.

> We build a package that gets installed on server with root:root.

Also the issue isn't clear to me,
because when you are root during install, you can set/alter the perms like you want, right? 

I guess the underlying issue is, when you install/deploy as root you need to adjust the permissions of your app, because installing as root means that users are not allowed to alter or exec the files. 
Why not simply change the ownership of the binary to the specific user/group for that folder or use a custom user to execute phantom stuff on the production machine?

Regards, Jens

**Comment by Trogie** [comment] 2016-10-28 04:25
Hello jakoch,

Sorry, I ment 0775 off course! Not 0776...

Composer doesnt run on the production machines. It runs on package-build machines and the debs get installed on the staging and production machines. 

On staging we run the smoke tests first automated against phantomjs and afterwards we run the whole test suite against a selenium grid and multiple devices/browsers/... Packages get installed as certain system users but all developers/testers should be able to run the scripts in which phantomjs gets started in webdriver mode. That's why I dont see why this package should have it's own permissions set.

**Comment by jakoch** [comment] 2017-01-10 10:04
I do not see the need to change this.
It seems to work quite well for the majority of users.
I've described two possible workarounds.
Closing.

**Closed by jakoch** 2017-01-10 10:04 UTC

**Comment by Trogie** [comment] 2017-01-10 10:13
Strange, we could have made it work for even more than just the majority of users while not breaking it for the previous majority... i.e. have made it better.

**Comment by chris-gilmore** [comment] 2017-05-03 11:29
Delete this [line](https://github.com/jakoch/phantomjs-installer/blob/f826b1fe7cc51497a0ee2d6b3de78314f79e380f/src/PhantomInstaller/Installer.php#L383) and everybody wins.
```php
chmod($targetName, static::PHANTOMJS_CHMODE);
```

**Comment by jakoch** [comment] 2017-08-16 09:07
This change was applied (https://github.com/jakoch/phantomjs-installer/commit/bca1f360dffd56dae37b5eb01316eeef75ec3776#diff-05763998e682ea40296deedf66294cf4R382).
It ships starting with version 2.1.1-p09.
